Занятие 1: Основы JavaScript
js-tasks-ru/jsbasic-20230911_ulyana0 pull request #2
Opened 2023-09-18 05:47 UTC by EkzLin

2023-09-18 05:48 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-09-18 09:35 UTC, SinimaWath requested changes

2023-09-18 09:35 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  return false;
Давай упростим без if: `return name != null && name.length >= 4 && !name.includes(' ')`

2023-09-18 09:35 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  return false;
`return strLow.includes('1xbet') || strLow.includes('xxx')`

2023-09-18 10:46 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-09-20 12:58 UTC, SinimaWath approved these changes

2023-09-20 12:58 UTC, merged